import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dfec5f",
        "on-surface-variant": "#adaaaa",
        "secondary-fixed-dim": "#d1dd53",
        "on-secondary-container": "#f6ff99",
        "on-primary-fixed-variant": "#456900",
        "inverse-surface": "#fcf8f8",
        "tertiary-fixed": "#fcef58",
        "on-secondary-fixed-variant": "#596000",
        "outline": "#777575",
        "primary-fixed-dim": "#a3f011",
        "secondary-dim": "#d1dd53",
        "secondary": "#dfec5f",
        "on-secondary": "#505600",
        "inverse-on-surface": "#565554",
        "surface-container-lowest": "#000000",
        "on-error": "#450900",
        "surface": "#0e0e0e",
        "on-primary": "#3d5e00",
        "on-primary-container": "#345100",
        "error-container": "#b92902",
        "surface-dim": "#0e0e0e",
        "tertiary-container": "#fcef58",
        "tertiary": "#fffae4",
        "secondary-container": "#5c6300",
        "on-tertiary-fixed": "#4b4600",
        "surface-variant": "#262626",
        "primary-container": "#9eea00",
        "tertiary-dim": "#eee04b",
        "primary": "#b1ff29",
        "on-background": "#ffffff",
        "inverse-primary": "#456900",
        "background": "#0a0a0a",
        "on-primary-fixed": "#304a00",
        "on-secondary-fixed": "#3e4300",
        "surface-container-low": "#131313",
        "outline-variant": "#494847",
        "on-surface": "#ffffff",
        "on-error-container": "#ffd2c8",
        "tertiary-fixed-dim": "#eee04b",
        "surface-container": "#1a1919",
        "primary-fixed": "#b1ff29",
        "surface-container-high": "#201f1f",
        "on-tertiary-container": "#5f5800",
        "surface-container-highest": "#262626",
        "primary-dim": "#a3f011",
        "on-tertiary-fixed-variant": "#6a6200",
        "surface-bright": "#2c2c2c",
        "error-dim": "#d53d18",
        "on-tertiary": "#686100",
        "error": "#ff7351",
        "surface-tint": "#b1ff29"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        "dmsans": ["DM Sans", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1rem", "full": "9999px" },
    },
  },
  plugins: [
    forms,
    containerQueries,
  ],
}
